package org.firstinspires.ftc.teamcode.lib.datatypes.util;

public enum Instructions {
    NONE,
    SHOOT_ONE,
    SHOOT_THREE,
    NEXT_TARGET,
    PREVIOUS_TARGET,
    SET_INTAKE_ON,
    SET_INTAKE_IDLE,
    SET_INTAKE_REVERSE,
    SET_TRANSFER_ON,
    SET_TRANSFER_IDLE,
    SET_TRANSFER_REVERSE,
    SET_SHOOTER_ON,
    SET_SHOOTER_IDLE,
    RESET_SHOOTER,
    SET_SHOOTER_VELOCITY,
    GET_SHOOTER_VELOCITY,
    RETURN_SHOOTER_VELOCITY,
    RESET_ORIENTATION,
    RECIEVE_POSITION,

    ENABLE_INTAKE_DEBUG,
    DISABLE_INTAKE_DEBUG,
    ENABLE_LIFT_DEBUG,
    DISABLE_LIFT_DEBUG,
    LOWER_INTAKE_DEBUG,
    ADJUST_FLAP_DEBUG,
    FEED_RING_DEBUG;
}

